threshold_width: '500'
minimum_width: '500'
maximum_width: '3000'
aspect_ratios: "21:9\r\n16:9\r\n16:3\r\n5:4\r\n5:2\r\n4:3\r\n3:2\r\n2:1\r\n1:1\r\n9:21\r\n9:16\r\n4:5\r\n3:16\r\n3:4\r\n2:5\r\n2:3\r\n1:2"
threshold_height: ''
minimum_height: ''
maximum_height: ''
